name: parqueadero_2025_g2
description: Proyecto Flutter para talleres - IntegraciÃ³n con Firebase

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  go_router: ^13.0.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  # Firebase dependencies
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.0

flutter:
  uses-material-design: true